CREATE DATABASE NOMINA;
USE NOMINA;

CREATE TABLE EMPLEADO(
	IDEMPLEADO INT AUTO_INCREMENT,
	NOMEMPRESA VARCHAR(40),
	FECHAINGRESO DATE,
	NOMBRE VARCHAR(30) NOT NULL,
  APATERNO VARCHAR(30) NOT NULL,
  AMATERNO VARCHAR(30) NOT NULL,
  EDAD DATE NOT NULL,
  TEL VARCHAR(15),
  CEL VARCHAR(12),
	CURP VARCHAR(30),
	RFC VARCHAR(13),
	CORREO VARCHAR(30),
	CARGO VARCHAR(30),
	CALLE TEXT,
  NUM_INT VARCHAR(5),
  NUM_EXT VARCHAR(5),
  COLONIA TEXT,
  MUNICIPIO TEXT,
  ESTADO TEXT,
	PRIMARY KEY(IDEMPLEADO)
);

CREATE TABLE ASISTENCIA(
	IDASISTENCIA INT AUTO_INCREMENT,
	IDEMPLEADO INT,
	DIASTRAB INT,
	FALTAS INT,
	PRIMARY KEY(IDASISTENCIA),
	FOREIGN KEY(IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
);

CREATE TABLE RECIBO(
	IDRECIBO INT AUTO_INCREMENT,
	IDEMPLEADO INT,
	IDSUELDO INT,
	PRIMARY KEY(IDRECIBO),
	FOREIGN KEY(IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
);

INSERT INTO EMPLEADO(IDEMPLEADO,NOMEMPRESA, FECHAINGRESO, NOMBRE, APATERNO, AMATERNO, EDAD,TEL, CEL, CURP, RFC, CORREO, CARGO, CALLE, NUM_INT, NUM_EXT,COLONIA, MUNICIPIO, ESTADO)
VALUES("1","ORACLE","2016-10-23","MANUEL","VILLANUEVA","SERRANO","1995-10-13","(55)58-78-18-22","55-8533-5630","VISM951013HDFLRN01","VISM951013V05","mvillanueva.1310@gmail.com","PROGRAMADOR","FLORES","SN","SN","LOMAS","MELCHOR OCAMPO","MEXICO");
